server:
  port: 7001
eureka:
  instance:
    hostname: localhost  # Eureka 服务端的实例名车
  client:
    register-with-eureka: false  # 是否向 Eureka 注册中心注册自己
    fetch-registry: false  # 如果为 false，表示自己为注册中心
    service-url:
      # 单机 监控页面  http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）
      # defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/

