server:
  port: 9527

spring:
  application:
    name: springcloud-zuul



# Eureka 配置，服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-zuul-9527 # 修改Eureka上的默认，描述信息
    prefer-ip-address: true  # true 可以显示ip地址

info:
  app.name: paulson-springcloud
  company.name: ybs

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept  # 不能再使用这个路径访问了
  prefix: /ybs  # 公共的访问前缀
#  ignored-services: *  # 隐藏全部
